### ISSUE TITLE
unclear parts of the config

### ISSUE THREAD

**Issue by rybit** [netlify/gocommerce#1]
in the config && example config there is an empty paypal `struct{}` and I am unclear on the `mail_subjects`. They seem to be documented as a struct with a single field, but the config shows a `map[string]string`

**Comment by biilmann** [comment]
The paypal struct is a placeholder until we add paypal support.

The mailer part of things still miss a few features. The `mail_subjects` struct will grow more fields as we start sending more different kinds of mails.
