### ISSUE TITLE
Pagination info for users endpoint is missing

### ISSUE THREAD

**Issue by RoseannaM** [netlify/gocommerce#122]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
It is currently returning the following as a Link header in the response. The only value that changes is "per_page". 
`</users?page=1&per_page=1>; rel="last"`
`x-total-count` is also always 1.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Make a request to the `/users` endpoint. 

**- What is the expected behavior?**
I expect the Link response header to be like the orders pagination information:
`</users/all/orders?page=2&per_page=50>; rel="next", </users/all/orders?page=6&per_page=50>; rel="last"`
And I expect `x-total-count` to return the correct total count.

**Comment by bcomnes** [comment]
To capture form our call today, lets look at this together when you pull it up again.
