### ISSUE TITLE
PayPal email receipt contains no product information and no seller info

### ISSUE THREAD

**Issue by pukhalski** [netlify/gocommerce#125]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
PayPal email receipt contains no product information. Product name and seller info is empty.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Purchase any product using paypal and see generated receipt mailed. See example attached.
![c_users_ingee_appdata_local_packages_microsoft skypeapp_kzf8qxf38zg5c_localstate_3bd58306-5c4e-4ede-a5a1-c351dc32961e](https://user-images.githubusercontent.com/1217692/45350196-829e8380-b5b3-11e8-9033-84883a8a20fe.jpg)

**- What is the expected behavior?**
Product names and seller info are filled out.

**- Please mention your Go version, and operating system version.**
Any.

**Comment by mraerino** [comment]
@pukhalski did you know that you can already pass a `description` parameter when calling `/paypal`?
This should set the description for the single amount that is displayed currently.

I will extend the paypal provider to accept an already created order for getting line items to pass to paypal.

**Comment by bcomnes** [comment]
I didnt mean to reopen this.
