### ISSUE TITLE
Retroactive order history

### ISSUE THREAD

**Issue by pukhalski** [netlify/gocommerce#126]
**- Do you want to request a *feature* or report a *bug*?**
Feature.

**- What is the current behavior?**
If user signs up with an email used for some other orders previously, these orders do not show up in API response.

**- What is the expected behavior?**
See also orders made previously for this email.

**- Please mention your Go version, and operating system version.**

**Comment by mraerino** [comment]
This is already possible by using the `/claim` endpoint. Therefore we decided not to take any action on this. If this is fine, please consider closing the issue.
Otherwise please describe what is missing in the claiming functionality.

**Comment by pukhalski** [comment]
If so, this should work out of the box, I think. Thanks!
