### ISSUE TITLE
Retroactive order uploads update

### ISSUE THREAD

**Issue by pukhalski** [netlify/gocommerce#128]
**- Do you want to request a *feature* or report a *bug*?**
Feature

**- What is the current behavior?**
User doesn't see any product uploads (or changes) if they were added after the actual purchase.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Purchase a digital product, then add another upload to it. User won't see it.

**- What is the expected behavior?**
Product uploads are retroactively propagated to all orders.

**Comment by biilmann** [comment]
We have a script that'll do this on demand for any order now. So for a start, let us know when it's needed and we'll trigger it.

I'll work to get that running as a background task in gocommerce itself.

**Comment by pukhalski** [comment]
@biilmann, can you share it? Or if it's not going to take a lot of time, I'd grab it from gocommerce.

**Comment by mraerino** [comment]
The endpoint introduced in #184 `/orders/:order_id/downloads/refresh` should enable you to give users a button for refreshing downloads in an order.
Closing this for now. Let me know if you need a different approach.
