### ISSUE TITLE
Tax calculation disregards discounts [CRITICAL]

### ISSUE THREAD

**Issue by pukhalski** [netlify/gocommerce#129]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
The total tax stays the same even if a discount code is applied
(while it actually should be based to the final price, including the
discount)

**- What is the expected behavior?**
Tax calculation should be based to the final price, including the
discount

Duplicate of https://github.com/netlify/gocommerce-js/issues/16

**Comment by indysigner** [comment]
Hi @phae, do we have any news on this? The total tax still stays the same even if a discount code is applied. See the below screenshots for comparison! + @biilmann @ChrBach @pukhalski 

![shop-with-discount](https://user-images.githubusercontent.com/4224281/46520609-e51a3500-c87c-11e8-8c91-c219311a2730.png)

![shop-without-discount](https://user-images.githubusercontent.com/4224281/46520610-e51a3500-c87c-11e8-9d31-121f06569998.png)

**Comment by indysigner** [comment]
I was just setting up two typical examples of how we may want to reroute tax calculation with fixed and relative discounts: ([link](https://docs.google.com/spreadsheets/d/1jHOle2rxKPYJEaFqGC3hq2k0BRTi3FEc_p24qQVQRvQ/edit#gid=0)) @mraerino

**Comment by bcomnes** [comment]
I didn't mean to reopen this.  Not sure how that happened.
