### ISSUE TITLE
Add a 'sort by' parameter to the orders api 

### ISSUE THREAD

**Issue by RoseannaM** [netlify/gocommerce#139]
**- Do you want to request a *feature* or report a *bug*?**
Feature

**- What is the expected behavior?**
The ability to sort orders by date, total 
Descending and ascending.

**Comment by mraerino** [comment]
I just discovered there is a sorting feature present on the order listing api.

Use the query parameter `sort` like this:
- **`/users/all/orders?sort=created_at`** *(default ascending)*
- **`/users/all/orders?sort=created_at%20desc`** *add `desc` or `asc` separated by a blank space*

The following fields are available for sorting:
- `created_at`
- `updated_at`
- `email`
- `taxes`
- `subtotal`
- `total`

**Comment by mraerino** [comment]
@RoseannaM can you close this issue if the existing functionality is enough?
