### ISSUE TITLE
Unknown error "Error processing line item"

### ISSUE THREAD

**Issue by tverney** [netlify/gocommerce#146]
- Do you want to request a feature or report a bug?
Bug

- What is the current behavior?
When POST a order, just receive a message "Error processing line item", but not says what is the error.

- What is the expected behavior?
Says exactly whats the problem to proccess the item.

**Comment by mraerino** [comment]
Quick hint: Have a look at the logs of your gocommerce deployment, there will most likely be a more detailed explanation for why the error happened there.

In this case it is most likely some issue with fetching the product metadata. The backend will try to fetch `SITE_URL + product.path` when you make the order. If there is an issue finding the metadata it will throw this error.

**Comment by tverney** [comment]
Cool explanation @mraerino. I`m having problem in setup this logging (I think i did alright, but the go application it`s not putting any log out there).

My config is (.env):

```
LOG_LEVEL=debug
LOG_FILE=~/error.log

```
The metadata you say it`s that json for each product like that:

`{"sku": "\/loja\/cafe-gourmet\/", "title": "Café Gourmet", "image":"https:\/\/netzei-cms-s3.s3.amazonaws.com\/18baa110b6558f18b15796bee59569cef2af2be9%2F2279%24IMG_20170205_084637.jpg", "prices": [{"amount":  39.9 , "currency": "BRL"}]}`

Right?

If you have any tips to config this logging to see the right error, can help me a lot. Thanks anyway! 👍

**Comment by mraerino** [comment]
I'm not at all sure about how to setup logging outside of a docker container. Does the binary not log to stderr if you just run it somewhere? I guess it should. In what kind of environment did you deploy it?

One thing to try about your metadata:
My setup seems to use a JSON string for the `amount` field in the prices array. This might be because of how floats can mess up calculations of sums. Internally gocommerce is using cents as int types to work around this.

**Comment by tverney** [comment]
I deploy it in a AWS instance (ubuntu one). 

Just do it the same as this guy here configured (I think it`s the only post on the internet that stays how to do this):  https://swizec.com/blog/setup-gocommerce-new-digital-ocean-droplet/swizec/8152

Well, I check it in all the machine, but not log it`s standing out.

About the amout, I will test this. Let`s see if change something for us.

**Comment by tverney** [comment]
@mraerino Marcus, I stringify it, but get the same "Error processing line item".

My JSON post to endpoint (using gocommerce-js): 

`{"email":"verney@netzei.com","shipping_address":{"name":"Thiago Verney","address1":"Rua Presidente Coutinho - de 350/351 ao fim, 610","city":"Florianópolis","state":"SC","country":"BR","zip":"88015-231"},"vatnumber":null,"currency":"BRL","coupon":null,"line_items":[{"sku":"/loja/cafe-gourmet/","description":"","type":"cafe","title":"Café Gourmet","image":"https://netzei-cms-s3.s3.amazonaws.com/18baa110b6558f18b15796bee59569cef2af2be9%2F2279%24IMG_20170205_084637.jpg","prices":[{"amount":"39.9","currency":"BRL","cents":"3990"}],"path":"/loja","quantity":1}]}
`

**Comment by tverney** [comment]
The interesting that I did a CURL posting the example that have here on repo and got the same error. I think that can be possible a bug in this.

**Comment by tverney** [comment]
The problem it`s: "Error parsing product metadata: json: cannot unmarshal number into Go struct field PriceMetadata.amount of type string"

It`s what you told @mraerino. But I`m putting in a string, and the same error comes out. You can publish your JSON string to test here if does the same?

**Comment by mraerino** [comment]
I actually just set up a demo page for gocommerce here: https://gocommerce-demo.netlify.com/

Example metadata for a product looks like this:
```
<script class="gocommerce-product" type="application/json">
{
   "image":"/images/anomaly-602394-unsplash.jpg",
   "prices":[
      {
         "amount":"4",
         "currency":"EUR"
      },
      {
         "amount":"5",
         "currency":"USD"
      }
   ],
   "sku":"beer-lager",
   "title":"Lager",
   "type":"beers"
}
</script>
```

@tverney the payload of your request to the api is actually not the problem, but rather what metadata is published on your static page (whatever your `SITE_URL` is and the path - `/loja` in this case)

**Comment by tverney** [comment]
Sure @mraerino. I know about this metadata stuff. But the payload was just the same what I defined in metadata (both are defined the "amount" in JSON string), that`s what I didn`t understood the real problem. :(

**Comment by tverney** [comment]
Got the problem. In production was staling content for a version without this number in string. Now it`s perfect! Thanks @mraerino
