### ISSUE TITLE
Database error on reports/products

### ISSUE THREAD

**Issue by bcomnes** [netlify/gocommerce#166]
When making a request to /commerce/reports/products?from=1530240815 I get a 500 error:

```
{code: 500, msg: "Database error", error_id: "38918195-e2df-4420-a4dd-f3e53c459ab1"}
```

Starting from here: https://github.com/netlify/gocommerce/blob/773034ed6e8b0e809a20e7f2209a96e33b5fd1fd/api/reports.go

Again, this could be a botched migration error.

**Comment by mraerino** [comment]
Seems to be fixed with the latest release.
