### ISSUE TITLE
Indexes in postgresql are not namespaced

### ISSUE THREAD

**Issue by mraerino** [netlify/gocommerce#169]
The indexes that are being created by `gorm` on a postgres database based on the `index` tag are not being prefixed with the database namespace.

There are several solutions I can think of:
- In connection with #168 indexes are created dynamically while migrations are running and at that time prefixed with the namespace
- `gorm` is patched to offer a way to hook into the naming of indexes like with table names for models

**Comment by bcomnes** [comment]
We've also discussed moving to pop instead of gorm.
