### ISSUE TITLE
Support Strong Customer Authentication using stripe

### ISSUE THREAD

**Issue by rybit** [netlify/gocommerce#179]
**- Do you want to request a *feature* or report a *bug*?**

As of September 14th, 2019 stripe is going to require 3d secure for transactions in Europe. If we want to still be available to process European transactions we will need to update the Stripe integration. 

[From Stripe](https://stripe.com/docs/strong-customer-authentication)

> Strong Customer Authentication (SCA), a new rule coming into effect on September 14, 2019, as part of PSD2 regulation in Europe, will require changes to how your European customers authenticate online payments. Card payments will require a different user experience, namely 3D Secure, in order to meet SCA requirements. Transactions that don’t follow the new authentication guidelines may be declined by your customers’ banks.

**Comment by mraerino** [comment]
## Vendor docs

- [About PaymentIntens](https://stripe.com/docs/payments/payment-intents/web)
- [Migration guide](https://stripe.com/docs/payments/payment-intents/migration)

Together with a customer we decided to try to support the synchronous flow first. The asynchronous one may follow later.

## New payments flow

- Client: Create a payment method and pass that to `POST /orders/:order_id/payments`
- Server: Create a `PaymentIntent` with the payment method from the client - report back if the payment needs more actions (including the client secret for the payment intent)
- Client: Completes additional action and calls `POST /orders/:order_id/payments/confirm`
- Server: Responds with the result of checking if the transaction is completed, updates payment status on order

## API docs for updated/new endpoints
 *TBD*

**Comment by mraerino** [comment]
## API docs for updated/new endpoints

### `POST /orders/:order_id/payments`

**Payload:**
```js
{
  "provider": "stripe",
  "payment_method_id": "<the id>"
}
```

**Response:** Transaction object
*(state if 3D secure is pending)*
```js
{
  "id": "...", // transaction id
  "order_id": "...",
  "invoice_number": "...",
  "processor_id": "...",
  "user_id": "...",
  "amount": "...",
  "currency": "...",
  "status": "pending",
  "type": "...",
  "created_at": "...",
  "provider_metadata": {
    "payment_intent_secret": "<client secret>"
  }
}
```

### `POST /payments/:payment_id/confirm`

(payment id from previous response)

**Payload:** none

**Response:**

```js
{
  "id": "...",
  "order_id": "...",
  "invoice_number": "...",
  "processor_id": "...",
  "user_id": "...",
  "amount": "...",
  "currency": "...",
  "status": "paid",
  "type": "...",
  "created_at": "..."
}
```

**Comment by mraerino** [comment]
## Updates to the SDK ([gocommerce.js](https://github.com/netlify/gocommerce-js))

- `GoCommerce.payment(payment_details)`
- `GoCommerce.paymentConfirm(payment_id)`

Example:
```js
const { status, provider_metadata, id: paymentId } = GoCommerce.payment({ stripe_payment_method_id: "..." })
if (status === "pending") {
  const { payment_intent_secret } = provider_metadata
  // do 3D secure
  try {
    GoCommerce.paymentConfirm(paymentId)
  }
}
```
