### ISSUE TITLE
Supporting Bundled Products in VAT calcuations

### ISSUE THREAD

**Issue by biilmann** [netlify/gocommerce#29]
We currently support VAT calculations based on product type. Some products however are bundles that can contain different product types.

A common case is a bundle that has a Physical Book + an Ebook which typically fall into different VAT brackets.

Currently a product definition looks like this:

```html
<script id="netlify-commerce-product" type="application/json">
{"title": "A Book", "prices":[{"amount":"39.00","currency":"USD"}], "sku":"my-book", "type":"Book"}
</script>
```

We should allow specifying that a price is based on multiple product types:

```html
<script id="netlify-commerce-product" type="application/json">
{"title": "A Book", "prices":[{"amount":"39.00","currency":"USD", items: [{"amount": "24.00", "type": "Book"}, {"amount": "15.00", "type": "Ebook"}], ], "sku":"my-book", "type":"Book"}
</script>
```

And take this optional "items" definition into account when calculating VAT.

**Comment by pukhalski** [comment]
It is critical to solve. Thanks

**Comment by biilmann** [comment]
This has already been implemented. Closing.
