### ISSUE TITLE
Discounts` Admin UI

### ISSUE THREAD

**Issue by indysigner** [netlify/gocommerce#48]
Hi @biilmann ,

As discussed in the Netlify office, here's my take on how an ideal Discounts Admin UI should be structured:

**Discount Code**:
- [ ] Input field

---

**Conditions**:
- [ ] Percentage value
- [ ] or Absolute value (with values for EUR & USD)

For:
- [ ] All Orders
- [ ] Orders Over ...
- [ ] Product Category
- [ ] Product

---

**Usage Limits**:
- [ ] Unlimited
- [ ] Limited number of uses
- [ ] 1 use only (tracked by customer's email)

---

- [ ] **Date range**: Start date, End date, No end date

![2017-04-14](https://cloud.githubusercontent.com/assets/4224281/25051655/0fd614d0-214e-11e7-96f3-59e25fb51c65.png)

**Comment by mraerino** [comment]
A quick solution would be to handle those inside the CMS because the coupons are already living in the git and accessed via the static page.
We could then make special issues if the coupon logic in gocommerce is not sufficient.
