### ISSUE TITLE
multitenancy support based on an instance ID

### ISSUE THREAD

**Issue by rybit** [netlify/gocommerce#54]
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
Currently, a single instance of gocommerce is for a single site. 

**- What is the expected behavior?**
We should have allow for a single instance of gocommerce to support multiple different sites base on the `aud` in the JWT token. 

I am not sure how this will work with anonymous checkouts, but it should be explored.

**Comment by brycekahle** [comment]
What needs to vary based on the `aud`? `site_url`, `payment` config, `mailer` config?

**Comment by rybit** [comment]
ok so all of that. And it turns out it can't be based on the `aud`. I'll

**Comment by rybit** [comment]
ok renamed. What I think we should do is make a version of this that has a `multi` command that will allow people to specify some headers that identify the instance they're talking to. This would allow us to preserve the current functionality (though with some refactoring).

How I see it is that people will specify some headers (configurable?) in the request. Then on the request we will look up the relevant configuration. We will also need to have the ability to provision a new instance (and update its config). 

I think that we can accomplish this by injecting something like a `ConfigurationManager` to the API itself. It would be something like 

```
type ConfigurationManager interface {
  Populate(context.Context) (context.Context, error)
}
```

In the single tenancy we would just delegate to the config file. In the multi case, we would delegate to a DB. 

This also means we need to split the configuration into what is 'core' (db locations) and 'instance' which is things like mailer or specific DB.

**Comment by brycekahle** [comment]
I'm realizing that because of the admin functions, we need to isolate everything based on the instance. I think we can do that two ways:
1. Use separate databases for each instance. I think `gorm` requires a new connection to select a different database, which likely has performance impacts. This plays nice with the single tenant version, as they operate largely the same.
2. Add an instance ID to all tables. One downside of this is having a extra unused ID for the single tenant version.

**Comment by brycekahle** [comment]
I suppose another option is to use prefixed table names using the instance ID.
