### ISSUE TITLE
render orders with different types

### ISSUE THREAD

**Issue by rybit** [netlify/gocommerce#75]
**- Do you want to request a *feature* or report a *bug*?**
Feature

**- What is the current behavior?**
Doesn't exist

**- What is the expected behavior?**
I want to be able to hit an endpoint explicitly dedicated to template rendering for an order and provide a template to return. 
Like this:
```
GET /order/:id/template?template=email-reciept
```

That would then hit the configured site's template directly (e.g. `/.netlify/gocommerce/templates/email-receipt`) and run it through the template engine. We would return the resulting HTML (or whatever you write...). 

This is very similar to the flow for doing confirmation emails. 

The reasoning is that this allows us to provide 'permanent' urls that would return things like reciepts or PDFs (eventually...) for different use cases. This is like setting the 'accepts' headers to render JSON vs XML vs HTML.

Yes, this could be handled on the frontend. It could just hit the order endpoint and render the returned JSON into something via JS/CSS/etc. But it would mean that the consumer would have to write in multiple formats/specifications. Now they just write/render all the templates in the same lang. 

![](https://s-media-cache-ak0.pinimg.com/originals/56/2e/e7/562ee7fae3f4d5922cc066b85c1f0c1a.jpg)

**Comment by brycekahle** [comment]
I believe #78 solves this
