### ISSUE TITLE
Support multiple filters for listing orders

### ISSUE THREAD

**Issue by rybit** [netlify/gocommerce#76]
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
We support some filters. 

**- What is the expected behavior?**
Support filtering by all of these: 
- [x] email
- [x] item
- [x] country
- [ ] customer name
- [ ] coupon name
- [x] order date range
- [ ] order vat %
- [ ] product type (physical product / bundle product / eBooks / Tickets / Subscription)

All of them need to support case insensitive searching. The product type one is a bit harder to see exactly, but should become clear quickly. 

**- Please mention your Go version, and operating system version.**

**Comment by brycekahle** [comment]
@biilmann There is already a boolean filter for whether taxes were applied or not. Is that sufficient for "order vat %", or do you want something additional?
