### ISSUE TITLE
remove configuration override

### ISSUE THREAD

**Issue by rybit** [netlify/gocommerce#80]
**- Do you want to request a *feature* or report a *bug*?**
feature *removal*

**- What is the current behavior?**
based on the `env` provided in the JWS header we will load a different configuration. Allowing for overrides.

**- What is the expected behavior?**
remove all of this. There is only one configuration for an instance. For different 'environments' you'd use different configurations.

**Comment by brycekahle** [comment]
I did not add the configuration override in #79
