### ISSUE TITLE
cannot use r (type *router) as type "context".Context in argument to chi.ServerBaseContext

### ISSUE THREAD

**Issue by sebastianmacias** [netlify/gocommerce#89]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
Unable to run install / run

**- If the current behavior is a bug, please provide the steps to reproduce.**

```
dev@DevX:[~]: go get -u github.com/netlify/gocommerce

go/src/github.com/netlify/gocommerce/api/api.go:145:57: cannot use r (type *router) as type "context".Context in argument to chi.ServerBaseContext:
	*router does not implement "context".Context (missing Deadline method)
go/src/github.com/netlify/gocommerce/api/api.go:145:57: cannot use ctx (type "context".Context) as type http.Handler in argument to chi.ServerBaseContext:
	"context".Context does not implement http.Handler (missing ServeHTTP method)

```

**- What is the expected behavior?**
Should be able to go get gocommerce

**- Please mention your Go version, and operating system version.**
Go 1.9 and 1.8.3, Ubuntu 16.04

Thanks

**Comment by brycekahle** [comment]
Closing. Issue was due to using non-pinned dependencies.
